version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=devdb
        - POSTGRES_USER=devuser
        - POSTGRES_PASSWORD=kalman
    ports:
        - 54032:5432
volumes:
  dev-db-data: