version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - URL=${URL}
    depends_on:
      - db
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - URL=${URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SETTINGS_MODULE=admin.settings
    command: >
      sh -c 'python consumer.py'
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 54032:5432
volumes:
  dev-db-data:
